"""Initial commit

Revision ID: 0298b63bdb82
Revises:
Create Date: 2023-05-12 17:26:08.089069

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.orm import Session

from models import RoleName, RoleOrm

# revision identifiers, used by Alembic.
revision = '0298b63bdb82'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'role',
        sa.Column('name', sa.Enum('user', 'admin', name='rolename'), nullable=False),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
    )
    op.create_table(
        'user',
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('password', sa.String(), nullable=False),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
    )
    op.create_table(
        'auth_history',
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column('user_agent', sa.String(), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=False),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('user_id', 'id'),
    )
    op.create_table(
        'user_role',
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column('role_id', sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('user_id', 'role_id'),
    )
    # ### end Alembic commands ###
    # Create and insert user and admin roles
    user_role = RoleOrm(name=RoleName.user)
    admin_role = RoleOrm(name=RoleName.admin)

    session = Session(bind=op.get_bind())
    session.add(user_role)
    session.add(admin_role)
    session.commit()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_role')
    op.drop_table('auth_history')
    op.drop_table('user')
    op.drop_table('role')
    # ### end Alembic commands ###
    op.execute('DROP TYPE rolename')
